### PR TITLE
feat: Added basic Django snippet.

### PR DESCRIPTION
**Pull request by k7kaushal**

### CODE REVIEW

**Comment by k7kaushal** [comment]
Please add hacktoberfest label. Thank you!

**Comment by kanha-gupta** [comment]
Hey @k7kaushal Thanks for your contribution. This pull request contains alot of code which is already merged. please update your local repository & only push what you want to add right now.
Thank you

**Comment by k7kaushal** [comment]
hi @kanha-gupta I have synced my fork still I'm getting those other commits in my PR, there is only one file changed as you can see, can you tell what is needed to be done?

**Comment by kanha-gupta** [comment]
@k7kaushal Now its fine. Great work !

**Pull request merged**
