### PR TITLE
Matrix implementation using 1 D array

### PR DESCRIPTION
**Pull request by yusra05**

### CODE REVIEW

**Comment by kanha-gupta** [comment]
Hey @yusra05 Please readjust the changes in every pull request by updating the main branch and then create a new branch directly from Main branch Or I can merge this singular pull request as this contains the code of all previous PRs too. 
Kindly update me on this :)

**Comment by yusra05** [comment]
@kanha-gupta merge this singular PR.

**Comment by kanha-gupta** [comment]
@yusra05 Thank you for your contribution. Can other PRs be closed ?

**Comment by yusra05** [comment]
@kanha-gupta closed 👍

**Pull request merged**
