### PR TITLE
PrefixToPostfix

### PR DESCRIPTION
**Pull request by guntarakesh**
Ref #2 , Added the Prefix to Postfix Problem solved using stack in C++.

### CODE REVIEW

**Comment by guntarakesh** [comment]
sir , review my PR and merge it .

**Comment by kanha-gupta** [comment]
@guntarakesh Please fix this PR and also your web dev snippet has been added previously.

**Comment by guntarakesh** [comment]
Sir , Can You please Explain to me What i have to do now .

**Comment by guntarakesh** [comment]
I added my Web dev Snippet previously but second time  i added Prefix to Postfix Code in C++ . I didn't understand the query here . please help me sir .

**Pull request closed without merging**
